services:
  db:
    container_name: ${PG_CONTAINER}
    image: postgres:${PG_TAG}
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: postgres
    ports:
      - ${PG_PORT_LOCALHOST}:${PG_PORT}
    volumes:
      - ./database/data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PG_USER} -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - etl-network

networks:
  etl-network:
    driver: bridge