name: CI

on:
  pull_request:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          pip install -r requirements-dev.txt

      - name: Lint
        run: ruff check .

      - name: Run tests
        run: |
            coverage run --omit="tests/*" -m pytest
            coverage report --fail-under=90
            coverage xml